server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/OnlineMarketPlace
    username: root
    password: silasener35

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true


    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        enable_lazy_load_no_trans: true
      jdbc:
        batch_size: 10
      order_updates: true
      order_inserts: true
      generate_statistics: true



logging:
  level:
    root: info


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

